export const courses = [
  {
    slug: "html",
    nama: "HTML",
    harga: "10 ribu",
    color: 'e34c26',
    materi: [
      "Apa itu HTML?",
      "Cara buat HTML",
      "Apa itu syntax?",
      "Apa itu tag",
      "Apa itu atribut",
      "Tag h1 - h6 (heading)",
      "Tag p (paragraf)",
      "Tag khusus text",
      "Tag hr dan br",
      "Tag tanpa penutup",
      'Atribut "id"',
      "Tag a (link)",
      "Tag input (text box)",
      "Tipe-tipe input",
      "Tag form",
      "Tag label",
      "tag textarea",
      "Tag img (gambar)",
      "Tag table (tabel)",
      "Tag video",
      "Tag audio",
      "Inline dan block",
      "Tag div",
      "Tag span",
      "Link absolut dan relatif",
      "Struktur HTML",
      "Head dan body",
      "HTML semantik",
      "Comment",
    ],
  },
  {
    slug: "css",
    nama: "CSS",
    color: '2965f1',
    harga: "15 ribu",
    materi: [
      "apa itu CSS",
      "syntax CSS",
      "atribut dan value",
      "style penulisan CSS",
      "atribut style pada HTML",
      "tag style pada HTML",
      "membuat CSS terpisah",
      "apa itu selector",
      "tag selector",
      "id selector",
      "class selector",
      "warna dan jenisnya",
      "atribut Background color",
      "unit/satuan pada CSS",
      "atribut width dan height",
      "min max pada height dan width",
      "apa itu shorthand",
      "prefix top,left,right,bottom",
      "atribut margin dan padding",
      "atribut border",
      "CSS box model",
      "styling text",
      "styling gambar",
      "styling list",
      "styling table",
      "atribut opacity",
      "block, inline dan hidden",
      "apa itu pseudo class",
      "styling link",
      "atribut position",
      "atribut z-index",
      "atribut overflow",
      "atribut selector",
      "global selector",
      "menggabungkan selector",
      "tingkatan selector",
      'aturan "!important"',
      "fungsi calc()",
      "fungsi max()",
      "fungsi min()",
      "atribut border radius",
      "warna lanjutan",
      "warna gradient",
      "atribut shadow",
      "atribut transform",
      "transisi pada CSS",
      "animasi",
      "multiple kolom",
      "atribute resize",
      "CSS variable",
      "box sizing",
      "media query",
      "CSS flexbox",
      "CSS grid",
    ],
  },
  {
    slug: "bs",
    color: '563d7c',
    nama: "Bootstrap",
    harga: "20 ribu",
    materi: [],
  },
  {
    slug: "tw",
    color: 'A5F3FC',
    nama: "Tailwind",
    harga: "20 ribu",
    materi: [],
  },
  {
    slug: "js",
    color: 'f0db4f',
    nama: "Javascript",
    harga: "25 ribu",
    materi: [],
  },
  {
    slug: "nodejs",
    nama: "Node JS",
    color: '42b883',
    harga: "30 ribu",
    materi: [],
  },
  {
    slug: "svelte",
    nama: "Svelte",
    color: 'aa1e1e',
    harga: "30 ribu",
    materi: [],
  },
];